<?php
// Free-text searches: keywords, stop words, phrases, negatives, wildcards, HTML and translated values.
require __DIR__ . '/fixture.php';
fx_index();

echo "\n################ A/B: FREE TEXT ################\n";
ab('A1 single keyword', 'sunset');
ab('A2 two keywords', 'red car');
ab('A3 stop word', 'the sunset');
ab('A4 stop word, other position', 'sunset of harbour');
ab('A5 resource type name', 'video');
ab('A6 resource type name + keyword', 'video production');
ab('A7 number among keywords (ref 8 = "Sunset")', 'sunset 8');
ab('A8 hyphenated single token', 'foo-bar');
ab('A9 hyphenated token + word', 'foo-bar industries');
ab('A10 filename', 'IMG_1234.jpg');
ab('A11 apostrophe', "o'brien");
ab('A12 email', 'john.smith@example.com');
ab('A13 quoted phrase', '"red car"');
ab('A14 quoted phrase, reversed words', '"car red"');
ab('A15 quoted phrase with stop word inside', '"foo and bar"');
ab('A16 negative', 'launch -ship');
ab('A17 negative only', '-sunset');
ab('A18 negative of a word only in a hidden field', 'ordinary -classified');
ab('A19 negative phrase', 'red -"sports car"');
ab('A20 OR', 'ship;book');
ab('A21 trailing wildcard', 'harb*');
ab('A22 leading wildcard', '*bour');
ab('A23 middle wildcard', 'har*ur');
ab('A24 wildcard on a non-indexed field value', 'zeb*');
ab('A25 wildcard + word', 'laun* party');
ab('A26 related keyword', 'automobile');
ab('A27 word beyond the first 500 characters', 'zeppelin');
ab('A28 word within the first 500 characters', 'albatross');
ab('A29 html: word after a tag', 'hello');
ab('A30 html: tag name', 'strong');
ab('A31 html: word inside nested tag', 'world');
ab('A32 html: href content', 'gallery');
ab('A33 translated option, default language', 'germany');
ab('A34 translated option, other language', 'allemagne');
ab('A35 word in hidden field', 'classified');
ab('A36 word in inactive field', 'legacy');
ab('A37 date component', '2024');
ab('A38 partial-index fragment', 'sculpt');
ab('A39 partial-index whole word', 'sculpture');
ab('A40 uppercase', 'SUNSET');
ab('A41 empty search', '');
ab('A42 fixed-list option word', 'kingdom');
ab('A43 number with decimals in text', '12.5');
ab('A44 keyword that exists only as related', 'car');
