<?php
// Condense the A/B outputs in results/ab/ into one table per battery: results/summary.md.
// Usage: php summarise.php

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$out = "# A/B results, one line per case\n\n"
    . "Generated by `summarise.php` from the files in `results/ab/`. Counts are the number of resources returned.\n"
    . "\"Not consulted\" means core returned before asking the plugin; \"falls back\" means the plugin declined and core\n"
    . "answered, so the two sides cannot differ.\n";

$cell = function (string $text): string {
    return str_replace(array('|', "\n"), array('\|', ' '), $text);
};

foreach (glob(__DIR__ . '/results/ab/*.txt') as $file) {
    $text = file_get_contents($file);
    preg_match_all(
        '/^(?<label>[^\n]+?):  (?<search>"(?:[^"\\\\]|\\\\.)*")(?<opts>  \[[^\n]*\])?\n    core:   (?<core>[^\n]*)\n    plugin: (?<plugin>[^\n]*)\n    => (?<verdict>[^\n]*)/m',
        $text,
        $cases,
        PREG_SET_ORDER
    );
    if (count($cases) === 0) {
        continue;
    }

    $out .= "\n## " . basename($file, '.txt') . "\n\n| Case | Search | Arguments | Core | Plugin | Result |\n|---|---|---|---|---|---|\n";
    foreach ($cases as $c) {
        $core = preg_match('/^total=(\d+)/', $c['core'], $m) ? $m[1]
            : (preg_match('/^non-array result (.*)$/', $c['core'], $m) ? 'no results, returns ' . $m[1] : $c['core']);

        if (strpos($c['plugin'], 'SERVED') === 0) {
            $plugin = preg_match('/total=(\d+)/', $c['plugin'], $m) ? $m[1] : 'served';
        } elseif (strpos($c['plugin'], 'fell back') === 0) {
            $reason = preg_match('/\((?:unsupported(?: by restriction)? \()?(.*?)\)*$/', $c['plugin'], $m) ? $m[1] : '';
            $plugin = 'falls back' . ($reason !== '' ? ': ' . $reason : '');
        } elseif (strpos($c['plugin'], 'not consulted') === 0) {
            $plugin = 'not consulted';
        } elseif (strpos($c['plugin'], 'PHP ERROR') === 0) {
            $plugin = preg_replace('/^PHP ERROR (.*?)(  total=.*)?$/', 'error: $1', $c['plugin']);
        } else {
            $plugin = $c['plugin'];
        }

        $verdict = $c['verdict'] === '—' ? '' : $c['verdict'];
        $out .= '| ' . $cell($c['label']) . ' | `' . $cell(json_decode($c['search']) ?? $c['search']) . '` | '
            . $cell(trim($c['opts'] ?? '', ' []')) . ' | ' . $cell($core) . ' | ' . $cell($plugin) . ' | ' . $cell($verdict) . " |\n";
    }
}

file_put_contents(__DIR__ . '/results/summary.md', $out);
echo 'wrote results/summary.md (' . substr_count($out, "\n| ") . " rows)\n";
